<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Apply_Online</name>
   <tag></tag>
   <elementGuidId>637ac6fd-f9b0-4c2b-8d0b-228217529508</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;MobileID\&quot;: \&quot;\&quot;,\n    \&quot;SourceApps\&quot;: \&quot;ME\&quot;,\n    \&quot;UserInfo\&quot;: {\n        \&quot;ipAddress\&quot;: \&quot;${ip_addres}\&quot;,\n        \&quot;userid\&quot;: \&quot;${user_id}\&quot;\n    },\n    \&quot;initiation\&quot;: {\n        \&quot;Cabang\&quot;: \&quot;${i_cabang}\&quot;,\n        \&quot;TypeConsumen\&quot;: \&quot;${i_typekonsumen}\&quot;,\n        \&quot;StatusPerkawinan\&quot;: \&quot;${i_statusperkawinan}\&quot;,\n        \&quot;Penjamin\&quot;: \&quot;\&quot;,\n        \&quot;TypePenjamin\&quot;: \&quot;\&quot;,\n        \&quot;Cluster\&quot;: \&quot;\&quot;,\n        \&quot;Product\&quot;: \&quot;\&quot;,\n        \&quot;TopUp\&quot;: \&quot;\&quot;\n    },\n    \&quot;PersonalData\&quot;: {\n        \&quot;alamatKTP\&quot;: \&quot;${p_alamat}\&quot;,\n        \&quot;kecamatan\&quot;: \&quot;${p_kecamatan}\&quot;,\n        \&quot;Agama\&quot;: \&quot;${p_agama}\&quot;,\n        \&quot;BirthDate\&quot;: \&quot;${p_tanggallahir}\&quot;,\n        \&quot;BirthPlace\&quot;: \&quot;${p_tempatlahir}\&quot;,\n        \&quot;IdentityNo\&quot;: \&quot;${p_noidentitas}\&quot;,\n        \&quot;IdentityType\&quot;: \&quot;${p_typeidentitas}\&quot;,\n        \&quot;Jenkel\&quot;: \&quot;${p_jeniskelamin}\&quot;,\n        \&quot;Kabupaten\&quot;: \&quot;${p_kabupaten}\&quot;,\n        \&quot;Kelurahan\&quot;: \&quot;${p_kelurahan}\&quot;,\n        \&quot;KodePos\&quot;: \&quot;${p_kodepos}\&quot;,\n        \&quot;Nama\&quot;: \&quot;${p_nama}\&quot;,\n        \&quot;NamaIbuKandung\&quot;: \&quot;${p_namaibu}\&quot;,\n        \&quot;Provinsi\&quot;: \&quot;${p_provinsi}\&quot;\n    },\n    \&quot;Occuption\&quot;: {\n        \&quot;NamaPerusahaan\&quot;: \&quot;${o_namaperusahaan}\&quot;,\n        \&quot;jabatan\&quot;: \&quot;${o_jabatan}\&quot;,\n        \&quot;totalPenghasilan\&quot;: \&quot;${o_totalpenghasilan}\&quot;,\n        \&quot;Alamat\&quot;: \&quot;${o_alamat}\&quot;,\n        \&quot;EconomyCode\&quot;: \&quot;${o_ekonomikode}\&quot;,\n        \&quot;EstablishedSince\&quot;: \&quot;${o_establishedsince}\&quot;,\n        \&quot;ExtTelp\&quot;: \&quot;${o_exttelp}\&quot;,\n        \&quot;JenisUsaha\&quot;: \&quot;${o_jenisusaha}\&quot;,\n        \&quot;Kecamatan\&quot;: \&quot;${o_kecamatan}\&quot;,\n        \&quot;KodeFax\&quot;: \&quot;${o_kodefax}\&quot;,\n        \&quot;KodeNoTelp\&quot;: \&quot;${o_kodenotelp}\&quot;,\n        \&quot;KodePos\&quot;: \&quot;${o_kodepos}\&quot;,\n        \&quot;NoTelp\&quot;: \&quot;${o_notelp}\&quot;,\n        \&quot;Pekerjaan\&quot;: \&quot;${o_pekerjaan}\&quot;\n    },\n    \&quot;SposeData\&quot;: {\n        \&quot;Kodepos\&quot;: \&quot;${s_kodepos}\&quot;,\n        \&quot;alamatPerusahaan\&quot;: \&quot;${s_alamatperusahaan}\&quot;,\n        \&quot;Agama\&quot;: \&quot;${s_agama}\&quot;,\n        \&quot;Alamat\&quot;: \&quot;${s_alamat}\&quot;,\n        \&quot;BirthDate\&quot;: \&quot;${s_tanggallahir}\&quot;,\n        \&quot;BirthPlace\&quot;: \&quot;${s_kotalahir}\&quot;,\n        \&quot;ExtTelpPerusahaan\&quot;: \&quot;${s_exttelp}\&quot;,\n        \&quot;FaxPerusahaan\&quot;: \&quot;${s_faxperusahaan}\&quot;,\n        \&quot;IdentityTypeSpouse\&quot;: \&quot;${s_kartuidentitas}\&quot;,\n        \&quot;Jabatan\&quot;: \&quot;${s_jabatan}\&quot;,\n        \&quot;JenKel\&quot;: \&quot;${s_jeniskelamin}\&quot;,\n        \&quot;Kabupaten\&quot;: \&quot;${s_kabupaten}\&quot;,\n        \&quot;Kecamatan\&quot;: \&quot;${s_kecamatan}\&quot;,\n        \&quot;KecamatanPerusahaan\&quot;: \&quot;${s_kecamatanperusahaan}\&quot;,\n        \&quot;Kelurahan\&quot;: \&quot;${s_kelurahan}\&quot;,\n        \&quot;KodeNomorTelpPerusahaan\&quot;: \&quot;${s_kodenotelpperusahaan}\&quot;,\n        \&quot;KodePosPerusahaan\&quot;: \&quot;${s_kodeposperusahaan}\&quot;,\n        \&quot;NamaPerusahaan\&quot;: \&quot;${s_namaperusahaan}\&quot;,\n        \&quot;NamaSpouse\&quot;: \&quot;${s_namaspouse}\&quot;,\n        \&quot;NomorKTP\&quot;: \&quot;${s_noktp}\&quot;,\n        \&quot;NotelpPerusahaan\&quot;: \&quot;${s_notelperusahaan}\&quot;,\n        \&quot;Occupation_KTP\&quot;: \&quot;${s_ocktp}\&quot;,\n        \&quot;Occupation_KartuNama\&quot;: \&quot;${s_ockartunama}\&quot;,\n        \&quot;PekerjaanSpouse\&quot;: \&quot;${s_ocpekerjaan}\&quot;,\n        \&quot;Provinsi\&quot;: \&quot;${s_ocprovinsi}\&quot;\n    },\n    \&quot;Dealer\&quot;: {\n        \&quot;DealerId\&quot;: \&quot;${d_dealerid}\&quot;,\n        \&quot;MainDealerId\&quot;: \&quot;${d_maindealerid}\&quot;,\n        \&quot;Alamat\&quot;: \&quot;${d_dealeralamat}\&quot;,\n        \&quot;Authorize\&quot;: \&quot;${d_dealerauth}\&quot;,\n        \&quot;Cabang\&quot;: \&quot;${d_dealercabang}\&quot;,\n        \&quot;DealerName\&quot;: \&quot;${d_dealernama}\&quot;,\n        \&quot;Fax\&quot;: \&quot;${d_dealerfax}\&quot;,\n        \&quot;Kota\&quot;: \&quot;${d_dealerkota}\&quot;,\n        \&quot;NoHP\&quot;: \&quot;${d_dealernohp}\&quot;,\n        \&quot;NoRek\&quot;: \&quot;${d_dealernorek}\&quot;\n    },\n    \&quot;Vehicle\&quot;: {\n        \&quot;BPKBNumber\&quot;: \&quot;${v_bpkbnumber}\&quot;,\n        \&quot;Brand\&quot;: \&quot;${v_brand}\&quot;,\n        \&quot;CarCondition\&quot;: \&quot;${v_carcondition}\&quot;,\n        \&quot;Kind\&quot;: \&quot;${v_kind}\&quot;,\n        \&quot;Model\&quot;: \&quot;${v_model}\&quot;,\n        \&quot;PoliceNo\&quot;: \&quot;${v_nopol}\&quot;,\n        \&quot;Purpose\&quot;: \&quot;${v_purpose}\&quot;,\n        \&quot;Type\&quot;: \&quot;${v_type}\&quot;,\n        \&quot;TypeId\&quot;: \&quot;${v_typeid}\&quot;,\n        \&quot;Year\&quot;: \&quot;${v_tahun}\&quot;\n    },\n    \&quot;LoanData\&quot;: {\n        \&quot;plafon\&quot;: \&quot;${l_plafon}\&quot;,\n        \&quot;AdmFee\&quot;: \&quot;${l_admfee}\&quot;,\n        \&quot;BiayaProcessPembiayaan\&quot;: \&quot;${l_biayaprocess}\&quot;,\n        \&quot;Blacklist\&quot;: \&quot;${l_blacklist}\&quot;,\n        \&quot;CarInsFee\&quot;: \&quot;${l_carinsfee}\&quot;,\n        \&quot;DP\&quot;: \&quot;${l_dp}\&quot;,\n        \&quot;DP_Percent\&quot;: \&quot;${l_dppercent}\&quot;,\n        \&quot;EffectiveRate\&quot;: \&quot;${l_effectiverate}\&quot;,\n        \&quot;FirstPayment\&quot;: \&quot;${l_firstpayment}\&quot;,\n        \&quot;FlatRate\&quot;: \&quot;${l_flatrate}\&quot;,\n        \&quot;HargaChasis\&quot;: \&quot;${l_hargachasis}\&quot;,\n        \&quot;HargaKaroseri\&quot;: \&quot;${l_hargakaroseri}\&quot;,\n        \&quot;Installment\&quot;: \&quot;${l_installment}\&quot;,\n        \&quot;KolomMutasiDebit\&quot;: \&quot;${l_kolommutasidebit}\&quot;,\n        \&quot;KolomMutasiKredit\&quot;: \&quot;${l_kolommutasikredit}\&quot;,\n        \&quot;KolomMutasiSaldo\&quot;: \&quot;${l_kolommutasisaldo}\&quot;,\n        \&quot;LifeInsurance\&quot;: \&quot;${l_lifeinsurance}\&quot;,\n        \&quot;LifeInsuranceFee\&quot;: \&quot;${l_lifeinsurancefee}\&quot;,\n        \&quot;LoanType\&quot;: \&quot;${l_loantype}\&quot;,\n        \&quot;OTR\&quot;: \&quot;${l_otr}\&quot;,\n        \&quot;Principal\&quot;: \&quot;${l_principal}\&quot;,\n        \&quot;ProvisionPercent\&quot;: \&quot;${l_provisionpercent}\&quot;,\n        \&quot;ProvisionalFee\&quot;: \&quot;${l_provisionfee}\&quot;,\n        \&quot;ProvisionalPayment\&quot;: \&quot;${l_provisionpayment}\&quot;,\n        \&quot;RepeatOrder\&quot;: \&quot;\&quot;,\n        \&quot;ResidualValue\&quot;: \&quot;${l_residualvalue}\&quot;,\n        \&quot;Tenor\&quot;: \&quot;${l_tenor}\&quot;,\n        \&quot;TotalOutstanding\&quot;: \&quot;${l_totaloutstanding}\&quot;,\n        \&quot;Tujuan\&quot;: \&quot;${l_tujuan}\&quot;\n    },\n    \&quot;FinancialData\&quot;: {\n        \&quot;cabangKCUBCA\&quot;: \&quot;${f_cabangkcubca}\&quot;,\n        \&quot;NomorRekening\&quot;: \&quot;${f_norek}\&quot;\n    },\n    \&quot;contactPersonData\&quot;: {\n        \&quot;HubunganDenganDebitor\&quot;: \&quot;${c_contactperson}\&quot;\n    },\n    \&quot;Insurance\&quot;: {\n        \&quot;BranchCarInsurance\&quot;: \&quot;${in_branchcarinsurance}\&quot;,\n        \&quot;BranchLifeInsurance\&quot;: \&quot;${in_branchlifeinsurance}\&quot;,\n        \&quot;CarInsuranceCorp\&quot;: \&quot;${in_carins}\&quot;,\n        \&quot;InsuranceDeduction\&quot;: \&quot;${in_insdeduc}\&quot;,\n        \&quot;InsurancePayment\&quot;: \&quot;${in_inspayment}\&quot;,\n        \&quot;InsuranceType\&quot;: \&quot;${in_instype}\&quot;,\n        \&quot;LifeInsuranceCorp\&quot;: \&quot;${in_lifeins}\&quot;,\n        \&quot;RSCC\&quot;: \&quot;${in_rscc}\&quot;,\n        \&quot;RSMB\&quot;: \&quot;${in_rsmb}\&quot;,\n        \&quot;TJH\&quot;: \&quot;${in_tjh}\&quot;\n    },\n    \&quot;OtherData\&quot;: {\n        \&quot;userInput\&quot;: \&quot;${od_userinput}\&quot;,\n        \&quot;Bukti\&quot;: \&quot;${od_bukti}\&quot;,\n        \&quot;LuasTanah\&quot;: \&quot;${od_luastanah}\&quot;,\n        \&quot;LuasBangunan\&quot;: \&quot;${od_luasbangunan}\&quot;,\n        \&quot;namaMo\&quot;: \&quot;${od_namamo}\&quot;,\n        \&quot;namaBM\&quot;: \&quot;${od_namabm}\&quot;,\n        \&quot;sumberAplikasi\&quot;: \&quot;${od_sumberapp}\&quot;,\n        \&quot;aplikasiInBranch\&quot;: \&quot;${od_appbranch}\&quot;,\n        \&quot;idAplikasi\&quot;: \&quot;${od_idapp}\&quot;\n    },\n    \&quot;General\&quot;: {\n        \&quot;JenisCluster\&quot;: \&quot;\&quot;,\n        \&quot;Packet\&quot;: \&quot;\&quot;,\n        \&quot;SalesAgent\&quot;: \&quot;\&quot;,\n        \&quot;SalesOffice\&quot;: \&quot;\&quot;,\n        \&quot;SalesType\&quot;: \&quot;\&quot;\n    },\n    \&quot;BPKB\&quot;: {\n        \&quot;BPKBOwner\&quot;: \&quot;${bp_bpkbowner}\&quot;,\n        \&quot;BodyNumber\&quot;: \&quot;${bp_bodynumber}\&quot;,\n        \&quot;Color\&quot;: \&quot;${bp_warna}\&quot;,\n        \&quot;Engineno\&quot;: \&quot;${bp_nomesin}\&quot;\n    },\n    \&quot;KartuKeluarga\&quot;: {\n        \&quot;Pendidikan\&quot;: \&quot;${kk_pendidikan}\&quot;\n    },\n    \&quot;NPWP\&quot;: {\n        \&quot;Nomor\&quot;: \&quot;${np_npwpnumber}\&quot;\n    },\n    \&quot;CoverBukuTabungan\&quot;: {\n        \&quot;Cabang\&quot;: \&quot;${cb_cabang}\&quot;\n    },\n    \&quot;KartuNamaPasangan\&quot;: {\n        \&quot;KodeFax\&quot;: \&quot;${kn_kodefax}\&quot;\n    },\n    \&quot;FAP\&quot;: {\n        \&quot;PdHmAny\&quot;: \&quot;${fap_pdhmany}\&quot;,\n        \&quot;HomeAddress\&quot;: \&quot;${fap_alamatrumah}\&quot;,\n        \&quot;HomeStatus\&quot;: \&quot;${fap_statusrumah}\&quot;,\n        \&quot;Kelurahan\&quot;: \&quot;${fap_kelurahan}\&quot;,\n        \&quot;Kecamatan\&quot;: \&quot;${fap_kecamatan}\&quot;,\n        \&quot;Kabupaten\&quot;: \&quot;${fap_kabupaten}\&quot;,\n        \&quot;Provinsi\&quot;: \&quot;${fap_provinsi}\&quot;,\n        \&quot;KodePos\&quot;: \&quot;${fap_kodepos}\&quot;,\n        \&quot;LamaTinggalTahun\&quot;: \&quot;${fap_lamatinggaltahun}\&quot;,\n        \&quot;LamaTinggalBulan\&quot;: \&quot;${fap_lamatinggalbulan}\&quot;,\n        \&quot;SupportPerson\&quot;: \&quot;${fap_supportperson}\&quot;,\n        \&quot;MailAddress\&quot;: \&quot;${fap_alamatemail}\&quot;,\n        \&quot;OtherMailAddress\&quot;: \&quot;${fap_alamatemaillain}\&quot;,\n        \&quot;KodyaOther\&quot;: \&quot;${fap_kabemail}\&quot;,\n        \&quot;Provinsiother\&quot;: \&quot;${fap_provinsilain}\&quot;,\n        \&quot;PostalCodeother\&quot;: \&quot;${fap_kodeposlain}\&quot;,\n        \&quot;EmailOffice\&quot;: \&quot;${fap_emailkantor}\&quot;,\n        \&quot;KodeTelpOffice1\&quot;: \&quot;${fap_kodetelp1}\&quot;,\n        \&quot;NomortelpOffice1\&quot;: \&quot;${fap_notelop1}\&quot;,\n        \&quot;KodeTelpOffice2\&quot;: \&quot;${fap_kodetelp2}\&quot;,\n        \&quot;NomorTelpOffice2\&quot;: \&quot;${fap_notelop2}\&quot;,\n        \&quot;KodeTelpOffice3\&quot;: \&quot;${fap_kodetelp3}\&quot;,\n        \&quot;NomorTelepon3\&quot;: \&quot;${fap_notelop2}\&quot;,\n        \&quot;PrefixHandphone1\&quot;: \&quot;${fap_prefixtelp1}\&quot;,\n        \&quot;NomorHandphone1\&quot;: \&quot;${fap_nohp1}\&quot;,\n        \&quot;PrefixHandphone2\&quot;: \&quot;${fap_prefixtelp2}\&quot;,\n        \&quot;NomorHandphone2\&quot;: \&quot;${fap_nohp2}\&quot;,\n        \&quot;NamaContactPerson\&quot;: \&quot;${fap_namacontactperson}\&quot;,\n        \&quot;AlamatContactPerson\&quot;: \&quot;${fap_alamatcontactperson}\&quot;,\n        \&quot;KotaContactPerson\&quot;: \&quot;${fap_kotacontactperson}\&quot;,\n        \&quot;KodePosContactPerson\&quot;: \&quot;${fap_kodeposcontactperson}\&quot;,\n        \&quot;kodeTelpContactperson\&quot;: \&quot;${fap_kodetelpcontactperson}\&quot;,\n        \&quot;NomorTeleponContactPerson\&quot;: \&quot;${fap_nombertelpcontactperson}\&quot;,\n        \&quot;RelationshipwithDebitor\&quot;: \&quot;${fap_relations}\&quot;,\n        \&quot;LineOfBusiness\&quot;: \&quot;\&quot;,\n        \&quot;PaymentMethod\&quot;: \&quot;${fap_carabayar}\&quot;\n    },\n    \&quot;Source\&quot;: \&quot;KKB\&quot;\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${token}</value>
   </httpHeaderProperties>
   <katalonVersion>8.1.0</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://api-dev.bcaf.id:8445/applyonline</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'ab1Z9remBczyMMAVDibZZ07vjEdJ'</defaultValue>
      <description></description>
      <id>3db29940-17b8-4046-aee8-5387dbcc0610</id>
      <masked>false</masked>
      <name>token</name>
   </variables>
   <variables>
      <defaultValue>'125.166.193.223'</defaultValue>
      <description></description>
      <id>3036e22c-6f9a-449e-8974-47925c9b6436</id>
      <masked>false</masked>
      <name>ip_addres</name>
   </variables>
   <variables>
      <defaultValue>'see'</defaultValue>
      <description></description>
      <id>1193a06d-2b5e-4b43-850e-76bdeb22ae06</id>
      <masked>false</masked>
      <name>user_id</name>
   </variables>
   <variables>
      <defaultValue>'TASIKMALAYA'</defaultValue>
      <description></description>
      <id>67427ce8-83b0-47ed-bd0d-4fc15ad4fb2e</id>
      <masked>false</masked>
      <name>i_cabang</name>
   </variables>
   <variables>
      <defaultValue>'PERORANGAN'</defaultValue>
      <description></description>
      <id>e275772a-ed6c-48e3-811f-bbdba5168b3e</id>
      <masked>false</masked>
      <name>i_typekonsumen</name>
   </variables>
   <variables>
      <defaultValue>'MARRIED'</defaultValue>
      <description></description>
      <id>a07d64f4-44c9-4577-ad2c-d29b3c4e40d6</id>
      <masked>false</masked>
      <name>i_statusperkawinan</name>
   </variables>
   <variables>
      <defaultValue>'JAGAVI - / -'</defaultValue>
      <description></description>
      <id>cc37295b-a560-4fac-9282-4629f84b162f</id>
      <masked>false</masked>
      <name>p_alamat</name>
   </variables>
   <variables>
      <defaultValue>'MOTOLING'</defaultValue>
      <description></description>
      <id>e317593e-cabf-424e-a0ac-17284239d8b7</id>
      <masked>false</masked>
      <name>p_kecamatan</name>
   </variables>
   <variables>
      <defaultValue>'Kristen'</defaultValue>
      <description></description>
      <id>4405ea80-17f4-4d6b-a3fa-f125740c5fbc</id>
      <masked>false</masked>
      <name>p_agama</name>
   </variables>
   <variables>
      <defaultValue>'02-05-1982'</defaultValue>
      <description></description>
      <id>953699d4-7d28-41c9-9e94-21ffa3cc5b3f</id>
      <masked>false</masked>
      <name>p_tanggallahir</name>
   </variables>
   <variables>
      <defaultValue>'MOTOLING'</defaultValue>
      <description></description>
      <id>acdab9fa-da9a-47b6-a3f2-d625fcae24e0</id>
      <masked>false</masked>
      <name>p_tempatlahir</name>
   </variables>
   <variables>
      <defaultValue>'7105074205820001'</defaultValue>
      <description></description>
      <id>e06ef3c5-f48e-4ea5-ae2d-3bc88643aa0d</id>
      <masked>false</masked>
      <name>p_noidentitas</name>
   </variables>
   <variables>
      <defaultValue>'KTP'</defaultValue>
      <description></description>
      <id>38e60e46-0444-4721-b3a9-06ede37aa4aa</id>
      <masked>false</masked>
      <name>p_typeidentitas</name>
   </variables>
   <variables>
      <defaultValue>'Perempuan'</defaultValue>
      <description></description>
      <id>931cac51-f761-40ba-a614-3f7fc5979a81</id>
      <masked>false</masked>
      <name>p_jeniskelamin</name>
   </variables>
   <variables>
      <defaultValue>'KABUPATEN MINAHASA SELATAN'</defaultValue>
      <description></description>
      <id>f64cbeb6-4671-4dd2-8cd9-075ba9d270f5</id>
      <masked>false</masked>
      <name>p_kabupaten</name>
   </variables>
   <variables>
      <defaultValue>'MOTOLING II'</defaultValue>
      <description></description>
      <id>f8a79401-4ab9-4822-a40d-4f7887657f0a</id>
      <masked>false</masked>
      <name>p_kelurahan</name>
   </variables>
   <variables>
      <defaultValue>'10130'</defaultValue>
      <description></description>
      <id>382b12bc-dc6a-424e-81eb-0036805221ea</id>
      <masked>false</masked>
      <name>p_kodepos</name>
   </variables>
   <variables>
      <defaultValue>'JELTY JEINE KOROAK'</defaultValue>
      <description></description>
      <id>e473df75-0c30-4882-8f8c-5512bf98e4b9</id>
      <masked>false</masked>
      <name>p_nama</name>
   </variables>
   <variables>
      <defaultValue>'ibu'</defaultValue>
      <description></description>
      <id>5b14cb28-2f30-4c16-83f0-f5713db0f5c0</id>
      <masked>false</masked>
      <name>p_namaibu</name>
   </variables>
   <variables>
      <defaultValue>'PROVINSI SULAWESI UTARA'</defaultValue>
      <description></description>
      <id>1c736374-1262-4a51-9e1b-9ba8f0b15835</id>
      <masked>false</masked>
      <name>p_provinsi</name>
   </variables>
   <variables>
      <defaultValue>'emo'</defaultValue>
      <description></description>
      <id>8ef76f66-e3ef-4db9-8e87-8bd1bbae32a1</id>
      <masked>false</masked>
      <name>o_namaperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'so'</defaultValue>
      <description></description>
      <id>a202d029-cfea-474d-914f-59e5c07174f1</id>
      <masked>false</masked>
      <name>o_jabatan</name>
   </variables>
   <variables>
      <defaultValue>'20,000,000'</defaultValue>
      <description></description>
      <id>742fd132-d7d1-440b-bdf8-c4e748f71558</id>
      <masked>false</masked>
      <name>o_totalpenghasilan</name>
   </variables>
   <variables>
      <defaultValue>'j'</defaultValue>
      <description></description>
      <id>3e26a67d-a64b-4de0-a839-60194ab35437</id>
      <masked>false</masked>
      <name>o_alamat</name>
   </variables>
   <variables>
      <defaultValue>'111308'</defaultValue>
      <description></description>
      <id>53238e63-c217-4307-b5ca-4c0e58cbb3bf</id>
      <masked>false</masked>
      <name>o_ekonomikode</name>
   </variables>
   <variables>
      <defaultValue>'2014'</defaultValue>
      <description></description>
      <id>5e2254e9-4621-4222-a7b5-2031b879b64b</id>
      <masked>false</masked>
      <name>o_establishedsince</name>
   </variables>
   <variables>
      <defaultValue>'36'</defaultValue>
      <description></description>
      <id>57fe143d-edf9-4511-91e1-eadcf3a82c32</id>
      <masked>false</masked>
      <name>o_exttelp</name>
   </variables>
   <variables>
      <defaultValue>'it'</defaultValue>
      <description></description>
      <id>1029724b-6147-49c5-a563-5b7bed327b0b</id>
      <masked>false</masked>
      <name>o_jenisusaha</name>
   </variables>
   <variables>
      <defaultValue>'kec'</defaultValue>
      <description></description>
      <id>a9d5e675-a93b-421c-9c0f-fffe1329a044</id>
      <masked>false</masked>
      <name>o_kecamatan</name>
   </variables>
   <variables>
      <defaultValue>'021'</defaultValue>
      <description></description>
      <id>e400980c-24f1-4967-b65b-314b4ac03cae</id>
      <masked>false</masked>
      <name>o_kodefax</name>
   </variables>
   <variables>
      <defaultValue>'021'</defaultValue>
      <description></description>
      <id>7b9cb0f8-fee8-45fd-9217-98471567b995</id>
      <masked>false</masked>
      <name>o_kodenotelp</name>
   </variables>
   <variables>
      <defaultValue>'17112'</defaultValue>
      <description></description>
      <id>99468a6d-d671-4bc3-baab-d611a77f34eb</id>
      <masked>false</masked>
      <name>o_kodepos</name>
   </variables>
   <variables>
      <defaultValue>'8818135'</defaultValue>
      <description></description>
      <id>c4babdb1-723e-4f2e-bf15-8d158031fda5</id>
      <masked>false</masked>
      <name>o_notelp</name>
   </variables>
   <variables>
      <defaultValue>'WIRASWASTA'</defaultValue>
      <description></description>
      <id>6dd74f5a-2b1b-4e44-8fca-98108fa376d6</id>
      <masked>false</masked>
      <name>o_pekerjaan</name>
   </variables>
   <variables>
      <defaultValue>'10130'</defaultValue>
      <description></description>
      <id>a3cb152f-d349-419d-b54e-2abffb3a56f2</id>
      <masked>false</masked>
      <name>s_kodepos</name>
   </variables>
   <variables>
      <defaultValue>'n'</defaultValue>
      <description></description>
      <id>d8011b76-6604-49fe-a513-9d7b727f614b</id>
      <masked>false</masked>
      <name>s_alamatperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'Islam'</defaultValue>
      <description></description>
      <id>d3da657b-7de8-4898-8508-e19bdb02639d</id>
      <masked>false</masked>
      <name>s_agama</name>
   </variables>
   <variables>
      <defaultValue>'TERANG SARI BLOK JI4/OI'</defaultValue>
      <description></description>
      <id>b2789bdd-38e5-47bf-891c-0b50bb8fe177</id>
      <masked>false</masked>
      <name>s_alamat</name>
   </variables>
   <variables>
      <defaultValue>'01-03-1979'</defaultValue>
      <description></description>
      <id>45ba1c66-e697-44f1-be7f-d27b4c31bb08</id>
      <masked>false</masked>
      <name>s_tanggallahir</name>
   </variables>
   <variables>
      <defaultValue>'TASIKMALAYA'</defaultValue>
      <description></description>
      <id>226bd2b7-9a41-4da5-ac6f-888b81104f42</id>
      <masked>false</masked>
      <name>s_kotalahir</name>
   </variables>
   <variables>
      <defaultValue>'59'</defaultValue>
      <description></description>
      <id>4893e51c-7e03-4b21-b954-227385e81da6</id>
      <masked>false</masked>
      <name>s_exttelp</name>
   </variables>
   <variables>
      <defaultValue>'029'</defaultValue>
      <description></description>
      <id>09fd69e6-b69a-4a53-b4c3-127a6d354fdf</id>
      <masked>false</masked>
      <name>s_faxperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'KTP'</defaultValue>
      <description></description>
      <id>6e37cbc9-18b8-49f4-b547-fa7040fad104</id>
      <masked>false</masked>
      <name>s_kartuidentitas</name>
   </variables>
   <variables>
      <defaultValue>'Guru'</defaultValue>
      <description></description>
      <id>b0f602c5-0aae-48ad-910a-4f546f06e65a</id>
      <masked>false</masked>
      <name>s_jabatan</name>
   </variables>
   <variables>
      <defaultValue>'Laki-laki'</defaultValue>
      <description></description>
      <id>9a4520f8-0d8e-4026-9ff8-691951ef8553</id>
      <masked>false</masked>
      <name>s_jeniskelamin</name>
   </variables>
   <variables>
      <defaultValue>'KABUPATEN KARAWANG'</defaultValue>
      <description></description>
      <id>b54cec31-658f-4596-96ab-33345cb8afa6</id>
      <masked>false</masked>
      <name>s_kabupaten</name>
   </variables>
   <variables>
      <defaultValue>'KLARI'</defaultValue>
      <description></description>
      <id>63d06689-227f-4dd5-ae43-8de566ab7418</id>
      <masked>false</masked>
      <name>s_kecamatan</name>
   </variables>
   <variables>
      <defaultValue>'kec'</defaultValue>
      <description></description>
      <id>62bfa56c-75e9-4b96-80d8-34d396a2e307</id>
      <masked>false</masked>
      <name>s_kecamatanperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'CIBALONGSARI'</defaultValue>
      <description></description>
      <id>467a9c4c-789e-4cbd-af72-bd113089f0c7</id>
      <masked>false</masked>
      <name>s_kelurahan</name>
   </variables>
   <variables>
      <defaultValue>'89'</defaultValue>
      <description></description>
      <id>01560e2d-ad44-44bc-84de-9ab5ac58f462</id>
      <masked>false</masked>
      <name>s_kodenotelpperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'17112'</defaultValue>
      <description></description>
      <id>259bb107-5db5-4529-8420-87bdde449c6d</id>
      <masked>false</masked>
      <name>s_kodeposperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'emo pasangan'</defaultValue>
      <description></description>
      <id>6b25b667-cb10-496b-8112-03ee8a096be2</id>
      <masked>false</masked>
      <name>s_namaperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'ENJANG MUIS BAHRUL ULUM'</defaultValue>
      <description></description>
      <id>5da34bf4-4b5b-463c-9855-1b11f20c5e54</id>
      <masked>false</masked>
      <name>s_namaspouse</name>
   </variables>
   <variables>
      <defaultValue>'3215050103790002'</defaultValue>
      <description></description>
      <id>894a4d70-b196-4ae0-ad08-5c7358607c95</id>
      <masked>false</masked>
      <name>s_noktp</name>
   </variables>
   <variables>
      <defaultValue>'59'</defaultValue>
      <description></description>
      <id>abb10c07-115a-4ff6-b178-cc4f0e8133c8</id>
      <masked>false</masked>
      <name>s_notelperusahaan</name>
   </variables>
   <variables>
      <defaultValue>'KARYAWAN'</defaultValue>
      <description></description>
      <id>193d34f9-ede9-4e62-bb89-29a484fbfa37</id>
      <masked>false</masked>
      <name>s_ocktp</name>
   </variables>
   <variables>
      <defaultValue>'KARYAWAN'</defaultValue>
      <description></description>
      <id>8338163d-1feb-41f1-b88d-9bab2487a162</id>
      <masked>false</masked>
      <name>s_ockartunama</name>
   </variables>
   <variables>
      <defaultValue>'KARYAWAN'</defaultValue>
      <description></description>
      <id>5e7d6304-00f8-4b05-aaa7-45f0e0ebbaff</id>
      <masked>false</masked>
      <name>s_ocpekerjaan</name>
   </variables>
   <variables>
      <defaultValue>'PROVINSI JAWA BARAT'</defaultValue>
      <description></description>
      <id>1c019920-5c68-42a8-b2d9-3e5725b09f06</id>
      <masked>false</masked>
      <name>s_ocprovinsi</name>
   </variables>
   <variables>
      <defaultValue>'W011'</defaultValue>
      <description></description>
      <id>f63ecd60-7d8d-41f4-9509-1df507e28383</id>
      <masked>false</masked>
      <name>d_dealerid</name>
   </variables>
   <variables>
      <defaultValue>'WJML'</defaultValue>
      <description></description>
      <id>bfb4814f-cef3-4057-995d-eacce4177f46</id>
      <masked>false</masked>
      <name>d_maindealerid</name>
   </variables>
   <variables>
      <defaultValue>'Jl. Jend. A. Yani No.336-338'</defaultValue>
      <description></description>
      <id>c44a564d-b126-4e21-a62e-49176468b6ba</id>
      <masked>false</masked>
      <name>d_dealeralamat</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>93fb1e70-1bc4-4e51-8a8b-3600ffed7826</id>
      <masked>false</masked>
      <name>d_dealerauth</name>
   </variables>
   <variables>
      <defaultValue>'Wijaya Motor A. Yani'</defaultValue>
      <description></description>
      <id>ac0290f6-b379-4585-9968-ec40e72866ac</id>
      <masked>false</masked>
      <name>d_dealercabang</name>
   </variables>
   <variables>
      <defaultValue>'Wijaya Motor Lestari, PT'</defaultValue>
      <description></description>
      <id>af8330b4-5fcf-4da2-b16a-e040cd6d265f</id>
      <masked>false</masked>
      <name>d_dealernama</name>
   </variables>
   <variables>
      <defaultValue>'0218818135'</defaultValue>
      <description></description>
      <id>85e3c7fd-5722-4266-80d8-6f43c6b677ab</id>
      <masked>false</masked>
      <name>d_dealerfax</name>
   </variables>
   <variables>
      <defaultValue>'Bandung'</defaultValue>
      <description></description>
      <id>a573b7fb-c49f-4deb-8a5b-224460fc8227</id>
      <masked>false</masked>
      <name>d_dealerkota</name>
   </variables>
   <variables>
      <defaultValue>'0227103388'</defaultValue>
      <description></description>
      <id>09165654-ffac-454c-a7d6-720c00a96167</id>
      <masked>false</masked>
      <name>d_dealernohp</name>
   </variables>
   <variables>
      <defaultValue>'0083058886'</defaultValue>
      <description></description>
      <id>214bec09-150e-42ed-a713-ae8baab3a422</id>
      <masked>false</masked>
      <name>d_dealernorek</name>
   </variables>
   <variables>
      <defaultValue>'11122'</defaultValue>
      <description></description>
      <id>b5ee9234-4c03-46d5-8d22-858450964c61</id>
      <masked>false</masked>
      <name>v_bpkbnumber</name>
   </variables>
   <variables>
      <defaultValue>'andika bpkb'</defaultValue>
      <description></description>
      <id>65925353-ee25-4852-91fd-0a82fcab9356</id>
      <masked>false</masked>
      <name>v_brand</name>
   </variables>
   <variables>
      <defaultValue>'New'</defaultValue>
      <description></description>
      <id>9fab3403-74a7-49ae-9d42-1b151f5817b2</id>
      <masked>false</masked>
      <name>v_carcondition</name>
   </variables>
   <variables>
      <defaultValue>'Mb. Penumpang'</defaultValue>
      <description></description>
      <id>a9da1a91-b3e4-4d80-89de-74f5ef83cc4a</id>
      <masked>false</masked>
      <name>v_kind</name>
   </variables>
   <variables>
      <defaultValue>'ALL NEW ALTIS'</defaultValue>
      <description></description>
      <id>c9b8bbc5-2a73-4a9d-9a20-2f890a6b51bd</id>
      <masked>false</masked>
      <name>v_model</name>
   </variables>
   <variables>
      <defaultValue>'b 1234 c'</defaultValue>
      <description></description>
      <id>d7b78671-fc59-4b02-9164-888018a70f4d</id>
      <masked>false</masked>
      <name>v_nopol</name>
   </variables>
   <variables>
      <defaultValue>'TEST Purpose Vehicle'</defaultValue>
      <description></description>
      <id>28e2cd68-ab4d-4408-9429-e249bdd1d6b8</id>
      <masked>false</masked>
      <name>v_purpose</name>
   </variables>
   <variables>
      <defaultValue>'ALL NEW ALTIS 1.8 V A/'</defaultValue>
      <description></description>
      <id>10ee98e9-8f74-4aeb-b757-6b1dfd0b955e</id>
      <masked>false</masked>
      <name>v_type</name>
   </variables>
   <variables>
      <defaultValue>'ALL NEW ALTIS 1.8 V A/'</defaultValue>
      <description></description>
      <id>7f5d6322-0e13-4c86-9394-7ee04c8d5556</id>
      <masked>false</masked>
      <name>v_typeid</name>
   </variables>
   <variables>
      <defaultValue>'2019'</defaultValue>
      <description></description>
      <id>31ebe52e-9393-4d9f-a53c-e6075bd7eca0</id>
      <masked>false</masked>
      <name>v_tahun</name>
   </variables>
   <variables>
      <defaultValue>'4'</defaultValue>
      <description></description>
      <id>5ddb980c-ec33-43ac-9bcf-51ef610c13f1</id>
      <masked>false</masked>
      <name>l_plafon</name>
   </variables>
   <variables>
      <defaultValue>'100000'</defaultValue>
      <description></description>
      <id>fed349d6-30c7-404f-9095-80e37cb17043</id>
      <masked>false</masked>
      <name>l_admfee</name>
   </variables>
   <variables>
      <defaultValue>'466733'</defaultValue>
      <description></description>
      <id>c2c51c62-5ec1-4cd4-aa57-bd0a9e80a26f</id>
      <masked>false</masked>
      <name>l_biayaprocess</name>
   </variables>
   <variables>
      <defaultValue>'no'</defaultValue>
      <description></description>
      <id>cd4c5981-3603-40b5-abbb-faae0ae34c26</id>
      <masked>false</masked>
      <name>l_blacklist</name>
   </variables>
   <variables>
      <defaultValue>'14000'</defaultValue>
      <description></description>
      <id>a5a1773d-7d89-4868-ae36-0f11a42c5387</id>
      <masked>false</masked>
      <name>l_carinsfee</name>
   </variables>
   <variables>
      <defaultValue>'33900000'</defaultValue>
      <description></description>
      <id>8723efbc-17ec-4372-b1fd-f755d379255b</id>
      <masked>false</masked>
      <name>l_dp</name>
   </variables>
   <variables>
      <defaultValue>'30.00'</defaultValue>
      <description></description>
      <id>74c1036d-4ada-44cf-a022-9b63094f99b4</id>
      <masked>false</masked>
      <name>l_dppercent</name>
   </variables>
   <variables>
      <defaultValue>'3.700000'</defaultValue>
      <description></description>
      <id>a6075c25-a6d8-4fb4-84b7-0b8cc5cab4cc</id>
      <masked>false</masked>
      <name>l_effectiverate</name>
   </variables>
   <variables>
      <defaultValue>'114257733'</defaultValue>
      <description></description>
      <id>a935d739-745c-4e36-a789-e5276c909017</id>
      <masked>false</masked>
      <name>l_firstpayment</name>
   </variables>
   <variables>
      <defaultValue>'0.000000'</defaultValue>
      <description></description>
      <id>fbc42f16-6db3-4143-9ef3-cfabf332d153</id>
      <masked>false</masked>
      <name>l_flatrate</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>b92ca407-ca16-4271-9327-2b1a06cb068b</id>
      <masked>false</masked>
      <name>l_hargachasis</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>ddf994fe-e0ef-48ac-bf10-63dd20f2267a</id>
      <masked>false</masked>
      <name>l_hargakaroseri</name>
   </variables>
   <variables>
      <defaultValue>'79100000'</defaultValue>
      <description></description>
      <id>4d7737dd-2131-449a-89de-ffc08c93380e</id>
      <masked>false</masked>
      <name>l_installment</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>12a56456-4f25-4e0a-88fb-44f41b60494d</id>
      <masked>false</masked>
      <name>l_kolommutasidebit</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>30498e48-179b-4169-814b-a4525ddde57a</id>
      <masked>false</masked>
      <name>l_kolommutasikredit</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>36a92d5a-d5cd-4811-8423-22473ad4f2e1</id>
      <masked>false</masked>
      <name>l_kolommutasisaldo</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>d4bfe6fe-eaf1-4dee-948c-bb7b89518409</id>
      <masked>false</masked>
      <name>l_lifeinsurance</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>e939fcef-d168-4992-9337-e48e2cec2b59</id>
      <masked>false</masked>
      <name>l_lifeinsurancefee</name>
   </variables>
   <variables>
      <defaultValue>'In Advance'</defaultValue>
      <description></description>
      <id>b765903a-57b7-4edb-b109-b042b59d4d7e</id>
      <masked>false</masked>
      <name>l_loantype</name>
   </variables>
   <variables>
      <defaultValue>'113000000'</defaultValue>
      <description></description>
      <id>0145d51c-ed83-40dc-ad75-7f4ea6bf3b5c</id>
      <masked>false</masked>
      <name>l_otr</name>
   </variables>
   <variables>
      <defaultValue>'79100000'</defaultValue>
      <description></description>
      <id>e22843c0-ac28-4fc6-bcc6-bada0127fad2</id>
      <masked>false</masked>
      <name>l_principal</name>
   </variables>
   <variables>
      <defaultValue>'1.00'</defaultValue>
      <description></description>
      <id>86a77ef6-a2ea-4f9f-87ef-e1b957565039</id>
      <masked>false</masked>
      <name>l_provisionpercent</name>
   </variables>
   <variables>
      <defaultValue>'791000'</defaultValue>
      <description></description>
      <id>db326cb3-6357-47d6-9500-5d96a717705c</id>
      <masked>false</masked>
      <name>l_provisionfee</name>
   </variables>
   <variables>
      <defaultValue>'Prepaid'</defaultValue>
      <description></description>
      <id>f08e3761-0909-4e12-ab93-76093d708483</id>
      <masked>false</masked>
      <name>l_provisionpayment</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>3f7ddd40-e92c-4730-9f5e-b66f2d02c782</id>
      <masked>false</masked>
      <name>l_residualvalue</name>
   </variables>
   <variables>
      <defaultValue>'24'</defaultValue>
      <description></description>
      <id>0e963818-6cc6-40be-bf6c-55f2c11c3e4e</id>
      <masked>false</masked>
      <name>l_tenor</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>6240195a-435f-437e-9a1b-1a18c8dcd82b</id>
      <masked>false</masked>
      <name>l_totaloutstanding</name>
   </variables>
   <variables>
      <defaultValue>'TEST Tujuan Loan data'</defaultValue>
      <description></description>
      <id>23b3fac7-ee16-4914-aecf-5b2dc12a3d47</id>
      <masked>false</masked>
      <name>l_tujuan</name>
   </variables>
   <variables>
      <defaultValue>'JKT47'</defaultValue>
      <description></description>
      <id>3ae20934-a55f-4f5a-bfa8-1b2daf886b48</id>
      <masked>false</masked>
      <name>f_cabangkcubca</name>
   </variables>
   <variables>
      <defaultValue>'12345678'</defaultValue>
      <description></description>
      <id>b30e4492-9029-4be8-acd0-67a70fac79bb</id>
      <masked>false</masked>
      <name>f_norek</name>
   </variables>
   <variables>
      <defaultValue>'saudara'</defaultValue>
      <description></description>
      <id>6a811597-8daa-43d9-a799-1c7403a77bba</id>
      <masked>false</masked>
      <name>c_contactperson</name>
   </variables>
   <variables>
      <defaultValue>'(NACA003) TIPE 1 - W2 - CS'</defaultValue>
      <description></description>
      <id>b6759b74-36c7-4a83-91da-0262166e9e55</id>
      <masked>false</masked>
      <name>in_branchcarinsurance</name>
   </variables>
   <variables>
      <defaultValue>'(00042-1) FULL COVER'</defaultValue>
      <description></description>
      <id>dfba3693-0077-4d56-91a8-526779ebc881</id>
      <masked>false</masked>
      <name>in_branchlifeinsurance</name>
   </variables>
   <variables>
      <defaultValue>'NEW - ASURANSI CENTRAL ASIA'</defaultValue>
      <description></description>
      <id>ecdadff1-5b34-47d8-b47a-260ada7d178a</id>
      <masked>false</masked>
      <name>in_carins</name>
   </variables>
   <variables>
      <defaultValue>'2'</defaultValue>
      <description></description>
      <id>5f31836f-e8f0-427f-b36b-d701c012e5be</id>
      <masked>false</masked>
      <name>in_insdeduc</name>
   </variables>
   <variables>
      <defaultValue>'Prepaid'</defaultValue>
      <description></description>
      <id>d6e5b62d-503c-409a-ba32-2ba39483ca05</id>
      <masked>false</masked>
      <name>in_inspayment</name>
   </variables>
   <variables>
      <defaultValue>'FREE,FREE'</defaultValue>
      <description></description>
      <id>a4d51305-14b7-43fb-859b-7b27e6c874a4</id>
      <masked>false</masked>
      <name>in_instype</name>
   </variables>
   <variables>
      <defaultValue>'(00042) PT. COMMONWEALTH LIFE'</defaultValue>
      <description></description>
      <id>cf18f372-62db-480c-ac1c-5adc1bbd3f9d</id>
      <masked>false</masked>
      <name>in_lifeins</name>
   </variables>
   <variables>
      <defaultValue>'Yes'</defaultValue>
      <description></description>
      <id>6acd6516-54d5-4dd5-a1f4-0854ab8f1acb</id>
      <masked>false</masked>
      <name>in_rscc</name>
   </variables>
   <variables>
      <defaultValue>'Yes'</defaultValue>
      <description></description>
      <id>93ade158-f80a-4727-8674-9d8512c085be</id>
      <masked>false</masked>
      <name>in_rsmb</name>
   </variables>
   <variables>
      <defaultValue>'(20894) 25000000'</defaultValue>
      <description></description>
      <id>db32bdb0-2a9f-4b19-837a-0b56543bcdc7</id>
      <masked>false</masked>
      <name>in_tjh</name>
   </variables>
   <variables>
      <defaultValue>'Fitri'</defaultValue>
      <description></description>
      <id>0dffa696-8edb-43c8-8f56-afb89012ee52</id>
      <masked>false</masked>
      <name>od_userinput</name>
   </variables>
   <variables>
      <defaultValue>'HGB,AJB,PBB'</defaultValue>
      <description></description>
      <id>860de13a-65fd-4077-8a10-9fcef169691e</id>
      <masked>false</masked>
      <name>od_bukti</name>
   </variables>
   <variables>
      <defaultValue>'2000'</defaultValue>
      <description></description>
      <id>4a2b4193-0136-4903-ac5a-d8815f8a543f</id>
      <masked>false</masked>
      <name>od_luastanah</name>
   </variables>
   <variables>
      <defaultValue>'200'</defaultValue>
      <description></description>
      <id>c1a37fa4-8f1f-4716-b383-45f882ccb6e6</id>
      <masked>false</masked>
      <name>od_luasbangunan</name>
   </variables>
   <variables>
      <defaultValue>'emo_mkt'</defaultValue>
      <description></description>
      <id>6f353f43-411c-48b7-8794-15e9b2b16884</id>
      <masked>false</masked>
      <name>od_namamo</name>
   </variables>
   <variables>
      <defaultValue>'emo_bm'</defaultValue>
      <description></description>
      <id>8346c368-9310-4dac-8e4d-1c37cf07072a</id>
      <masked>false</masked>
      <name>od_namabm</name>
   </variables>
   <variables>
      <defaultValue>'WEBSITE'</defaultValue>
      <description></description>
      <id>be60e5e8-f6c3-4e4e-9557-8ef2207cf58f</id>
      <masked>false</masked>
      <name>od_sumberapp</name>
   </variables>
   <variables>
      <defaultValue>'AC0023K'</defaultValue>
      <description></description>
      <id>1a40348e-f350-4213-a441-9a19b749de35</id>
      <masked>false</masked>
      <name>od_idapp</name>
   </variables>
   <variables>
      <defaultValue>'KKB SOLO'</defaultValue>
      <description></description>
      <id>46abb544-cb75-4678-bee9-9bfa2439441d</id>
      <masked>false</masked>
      <name>od_appbranch</name>
   </variables>
   <variables>
      <defaultValue>'andika bpkb'</defaultValue>
      <description></description>
      <id>475e13e7-8e9d-4376-aa35-a79a7f2e5194</id>
      <masked>false</masked>
      <name>bp_bpkbowner</name>
   </variables>
   <variables>
      <defaultValue>'11122'</defaultValue>
      <description></description>
      <id>e0c3a52b-9478-4382-b9b8-52b689e5b93e</id>
      <masked>false</masked>
      <name>bp_bodynumber</name>
   </variables>
   <variables>
      <defaultValue>'hijau'</defaultValue>
      <description></description>
      <id>5fdab3ad-4c91-4f2b-be13-a245a9c27f0b</id>
      <masked>false</masked>
      <name>bp_warna</name>
   </variables>
   <variables>
      <defaultValue>'11122'</defaultValue>
      <description></description>
      <id>ac5b8237-4137-4454-a1be-30cf0321882d</id>
      <masked>false</masked>
      <name>bp_nomesin</name>
   </variables>
   <variables>
      <defaultValue>'S3'</defaultValue>
      <description></description>
      <id>92188417-44a7-4920-b6ad-ae24d81ee1fc</id>
      <masked>false</masked>
      <name>kk_pendidikan</name>
   </variables>
   <variables>
      <defaultValue>'123456789'</defaultValue>
      <description></description>
      <id>c0423b4c-500c-47ff-a5ce-6951a9b6cdfc</id>
      <masked>false</masked>
      <name>np_npwpnumber</name>
   </variables>
   <variables>
      <defaultValue>'JKT47'</defaultValue>
      <description></description>
      <id>c8ced07b-269d-4660-a042-bc5a43c2092c</id>
      <masked>false</masked>
      <name>cb_cabang</name>
   </variables>
   <variables>
      <defaultValue>'021'</defaultValue>
      <description></description>
      <id>b3e091d3-b469-4fda-8f06-9112b98b36ef</id>
      <masked>false</masked>
      <name>kn_kodefax</name>
   </variables>
   <variables>
      <defaultValue>'2'</defaultValue>
      <description></description>
      <id>5cc31e8c-46a6-4476-9152-3a6b42ceb139</id>
      <masked>false</masked>
      <name>fap_pdhmany</name>
   </variables>
   <variables>
      <defaultValue>'Jl'</defaultValue>
      <description></description>
      <id>0fc074cc-51c8-40bd-a075-a8b2e3905d76</id>
      <masked>false</masked>
      <name>fap_alamatrumah</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>39d13229-84d5-4f7d-b315-a21c11ffc146</id>
      <masked>false</masked>
      <name>fap_statusrumah</name>
   </variables>
   <variables>
      <defaultValue>'Kel'</defaultValue>
      <description></description>
      <id>5710ae43-1956-41b7-ae00-d80c992738e9</id>
      <masked>false</masked>
      <name>fap_kelurahan</name>
   </variables>
   <variables>
      <defaultValue>'Kec'</defaultValue>
      <description></description>
      <id>0f452a2f-7f74-44b7-aee6-f508e78805ee</id>
      <masked>false</masked>
      <name>fap_kecamatan</name>
   </variables>
   <variables>
      <defaultValue>'Kab'</defaultValue>
      <description></description>
      <id>765b3985-c82d-4c7d-b001-315e2f3c8254</id>
      <masked>false</masked>
      <name>fap_kabupaten</name>
   </variables>
   <variables>
      <defaultValue>'Prov'</defaultValue>
      <description></description>
      <id>cb4e4fa1-7958-4dcc-9ea6-ee03ce546387</id>
      <masked>false</masked>
      <name>fap_provinsi</name>
   </variables>
   <variables>
      <defaultValue>'12345'</defaultValue>
      <description></description>
      <id>546ff202-4b60-4349-ab3e-b2ec3932051e</id>
      <masked>false</masked>
      <name>fap_kodepos</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>987508af-a54c-485b-bec3-3a6ccaca6ec2</id>
      <masked>false</masked>
      <name>fap_lamatinggaltahun</name>
   </variables>
   <variables>
      <defaultValue>'12'</defaultValue>
      <description></description>
      <id>ae5ed1bd-65ab-41b9-9e13-225b29b8e82c</id>
      <masked>false</masked>
      <name>fap_lamatinggalbulan</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>4e05190e-2332-4742-81df-463b1b1d6d3a</id>
      <masked>false</masked>
      <name>fap_supportperson</name>
   </variables>
   <variables>
      <defaultValue>'3'</defaultValue>
      <description></description>
      <id>babc79e6-0593-493e-84ca-9902f8ef34df</id>
      <masked>false</masked>
      <name>fap_alamatemail</name>
   </variables>
   <variables>
      <defaultValue>'Other mail address'</defaultValue>
      <description></description>
      <id>a7cee3b9-d9d4-45ea-99cb-0143fc24025c</id>
      <masked>false</masked>
      <name>fap_alamatemaillain</name>
   </variables>
   <variables>
      <defaultValue>'kab mail other'</defaultValue>
      <description></description>
      <id>58a8983e-ea2f-4508-90f7-544f03f67b31</id>
      <masked>false</masked>
      <name>fap_kabemail</name>
   </variables>
   <variables>
      <defaultValue>'pro mail other'</defaultValue>
      <description></description>
      <id>724382ed-57ef-45ee-bd72-b7e5bb4dfd4d</id>
      <masked>false</masked>
      <name>fap_provinsilain</name>
   </variables>
   <variables>
      <defaultValue>'17112'</defaultValue>
      <description></description>
      <id>d1f0e2bf-03b4-4660-9af9-4b4b8a2e849d</id>
      <masked>false</masked>
      <name>fap_kodeposlain</name>
   </variables>
   <variables>
      <defaultValue>'selain@other.com'</defaultValue>
      <description></description>
      <id>17c24372-b934-4317-ac3a-fb8e1a853b72</id>
      <masked>false</masked>
      <name>fap_emailkantor</name>
   </variables>
   <variables>
      <defaultValue>'022'</defaultValue>
      <description></description>
      <id>1b13492e-5b54-4e61-ba80-b85e3cf127e6</id>
      <masked>false</masked>
      <name>fap_kodetelp1</name>
   </variables>
   <variables>
      <defaultValue>'8818135'</defaultValue>
      <description></description>
      <id>607f4d14-1068-4b28-bc9a-e30a07af9960</id>
      <masked>false</masked>
      <name>fap_notelop1</name>
   </variables>
   <variables>
      <defaultValue>'023'</defaultValue>
      <description></description>
      <id>841036e8-32ff-408a-bf2a-818d1daa7575</id>
      <masked>false</masked>
      <name>fap_kodetelp2</name>
   </variables>
   <variables>
      <defaultValue>'8818136'</defaultValue>
      <description></description>
      <id>a193df50-1dfa-4f27-9bcf-280ea3accb14</id>
      <masked>false</masked>
      <name>fap_notelop2</name>
   </variables>
   <variables>
      <defaultValue>'024'</defaultValue>
      <description></description>
      <id>29a86352-61f6-403d-b0a0-b97daacf2d0d</id>
      <masked>false</masked>
      <name>fap_kodetelp3</name>
   </variables>
   <variables>
      <defaultValue>'8818137'</defaultValue>
      <description></description>
      <id>84b893cc-a5c9-41e0-8081-b3fa16fd1b2f</id>
      <masked>false</masked>
      <name>fap_notelop3</name>
   </variables>
   <variables>
      <defaultValue>'0857'</defaultValue>
      <description></description>
      <id>0d4ad94b-f770-4b7c-8e2e-9c1779b64dba</id>
      <masked>false</masked>
      <name>fap_prefixtelp1</name>
   </variables>
   <variables>
      <defaultValue>'14873452'</defaultValue>
      <description></description>
      <id>2ad60afe-7e63-4674-9446-cf6b8f7585f9</id>
      <masked>false</masked>
      <name>fap_nohp1</name>
   </variables>
   <variables>
      <defaultValue>'0813'</defaultValue>
      <description></description>
      <id>6a06d3a0-938c-4807-8708-e0c544175d0b</id>
      <masked>false</masked>
      <name>fap_prefixtelp2</name>
   </variables>
   <variables>
      <defaultValue>'17161523'</defaultValue>
      <description></description>
      <id>4cb93a2d-430b-4780-99c4-b2702126c21d</id>
      <masked>false</masked>
      <name>fap_nohp2</name>
   </variables>
   <variables>
      <defaultValue>'andika'</defaultValue>
      <description></description>
      <id>ecaacee9-9bdb-44c7-ad52-b0ae2c027e17</id>
      <masked>false</masked>
      <name>fap_namacontactperson</name>
   </variables>
   <variables>
      <defaultValue>'jl andika'</defaultValue>
      <description></description>
      <id>b53802b6-f3ab-4977-a0cf-38d70b4342e1</id>
      <masked>false</masked>
      <name>fap_alamatcontactperson</name>
   </variables>
   <variables>
      <defaultValue>'kota andika'</defaultValue>
      <description></description>
      <id>e00a4e75-c2a8-4955-9274-685f9f5a1a3c</id>
      <masked>false</masked>
      <name>fap_kotacontactperson</name>
   </variables>
   <variables>
      <defaultValue>'17112'</defaultValue>
      <description></description>
      <id>fd352952-0453-42d0-ab74-98892f4d65a5</id>
      <masked>false</masked>
      <name>fap_kodeposcontactperson</name>
   </variables>
   <variables>
      <defaultValue>'021'</defaultValue>
      <description></description>
      <id>3e0678b7-a314-4773-aad9-9ef2a5c7bf3b</id>
      <masked>false</masked>
      <name>fap_kodetelpcontactperson</name>
   </variables>
   <variables>
      <defaultValue>'8812123'</defaultValue>
      <description></description>
      <id>8eafab41-641f-4cd7-8356-0bb7940577a8</id>
      <masked>false</masked>
      <name>fap_nombertelpcontactperson</name>
   </variables>
   <variables>
      <defaultValue>'saudara'</defaultValue>
      <description></description>
      <id>08849ece-7278-47cb-abf4-409d3273dfc0</id>
      <masked>false</masked>
      <name>fap_relations</name>
   </variables>
   <variables>
      <defaultValue>'A'</defaultValue>
      <description></description>
      <id>778bcdab-6bfe-42b2-8a88-895eaf6eacc1</id>
      <masked>false</masked>
      <name>fap_carabayar</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
